name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: pearlrx
          filename: github-metrics.svg
          template: classic
          base: header, activity, community, repositories
          plugin_languages: yes
          plugin_achievements: yes
          config_timezone: Europe/Berlin
